### ISSUE TITLE
Distribution - Publishing apps via MakeDrive

### ISSUE THREAD

**Issue by thisandagain** [mozillafordevelopment/player#1]
For the Webmaker App we need a way to let users distribute their applications using a URL. For our primary mobile use-case (particularly without copy/paste in Firefox OS) these URLs should be short and memorable. We are currently accomplishing this using a number of different patterns spread across our tools (Appmaker, Make Valet, etc.). Our integration with `makedrive` seems like a good opportunity to establish a pattern that would apply to various other products including Nimble and even Appmaker in the future. 

I have a feeling that quite a bit of thought has already been given to this re: Nimble that I'm not aware of yet. Opening this issue as a place to discuss across teams. :cake: :cat2: :boom: 

**Desired URL Pattern:**
https://[username].makes.org/[app name]
https://kitty.makes.org/cat-food-reviews

**Technical Considerations:**
Firefox OS - Add support of installing of multiple apps off of the same origin
(Scheduled to land in Firefox OS 2.1)
https://bugzilla.mozilla.org/show_bug.cgi?id=778277

**Questions:**
- Is this a service that we would like MakeDrive to provide or would we like this to exist as an independent service? My instinct is to spin up a service dedicated to this as to keep this read-heavy load contained and make it a bit easier to iterate on as I would expect each product will have some specific requirements.
- If we do want to spin up a service dedicated to this how would we like to manage caching? I see a couple reasonable options off the top of my head: 
  - Storing compressed pre-rendered blobs via Redis or Memcached (either work well with AWS ElastiCache IME)
  - Using a 3rd-party edge provider such as Fastly (arguably more ideal option given our international target audience)

(Ping @humphd @simonwex @k88hudson @secretrobotron)

**Comment by humphd** [comment]
This is going to straddle MakeDrive, MakeAPI, Make-Valet, our devops stuff, and likely other things.  @simonwex and @alicoding were going to start discussing it this week, and I think we need to get the results of that into this bug.  Also CC'ing some other people, who will no doubt be involved: @jbuck, @xmatthewx, @pomax

**Comment by alicoding** [comment]
Some action items from the conversation we had this morning

Action Items:
- What's in .make.json - Simon & Chris (Cade)
- Audit of MakeAPI - Simon & Cade
- Prototype Publish service - K88
- Add publish hook to MakeDrive - Ali
- Understand sucurity update mechanism - Simon & Cade
- Design "404 helpers" - Simon & Cade & Ali
- Talk "Why CF sucks" - Simon & Cade & Jbuck
- List of legacy URLS (Make-Valet) - Cade

```
simon.makes.org/catparty/
                        index.html
                        index.js
                        app.json
                        cat.jpg
                        .make.json
```

**Comment by alicoding** [comment]
And the design
![img_20140924_110926](https://cloud.githubusercontent.com/assets/4368149/4395331/3afc985e-442a-11e4-8550-be3ad9582d88.jpg)
